### ISSUE TITLE
TypeError: this._stopReaping is not a function

### ISSUE THREAD

**Issue by paulxuca** [Vincit/tarn.js#2]
```
this._stopReaping();
         ^
TypeError: this._stopReaping is not a function
    at process.destroy (/Users/test/node_modules/tarn/lib/Pool.js:166:10)
    at emitNone (events.js:86:13)
    at process.emit (events.js:188:7)
    at Signal.wrap.onsignal (internal/process.js:215:44)
```

`pool.destory()` is called via:

```
process.on('SIGTERM', pool.destroy);
```

What's a better way to clean up the pool when there is a `SIGTERM` os signal?

**Comment by koskimas** [comment]
The destroy method cannot be used without context. When you pass it like that, `this` doesn't point anywhere. You need to do something like this:

```js
process.on('SIGTERM', () => pool.destroy());
```

or

```js
process.on('SIGTERM', pool.destroy.bind(pool));
```
